### ISSUE TITLE
Pi zero cant connect

### ISSUE THREAD

**Issue by Stump2939** [jeroenterheerdt/neato-serial#2]
So ill be honest I have no idea when it comes to linux and these pi's but the end goal is to get my neato working with HA. I believe I have everything installed but here is the error I get when i try and run the neatoserial.py .
``
pi@raspberrypi:~/neato-serial $ sudo python3 neatoserial.py
Traceback (most recent call last):
  File "neatoserial.py", line 2, in <module>
    from config import settings
  File "/home/pi/neato-serial/config.py", line 2, in <module>
    import yaml
ImportError: No module named 'yaml'
pi@raspberrypi:~/neato-serial $ python3 neatoserial.py
Could not connect to device /dev/ttyACM0. Trying next device.
Could not connect to device /dev/ttyACM0. Trying next device.
Could not connect to device /dev/ttyACM1. Trying next device.
Could not connect to device /dev/ttyACM1. Trying next device.
Enter commands. Enter 'exit' to quit
?
``

**Comment by jeroenterheerdt** [comment]
do `ls /dev/ttyACM*`. This is the device that maps to your serial port.
