### ISSUE TITLE
How to connect Raspi to BotVac physically?

### ISSUE THREAD

**Issue by JekleFPV** [jeroenterheerdt/neato-serial#3]
I have a BotVac 85 on which I want to integrate my pi zero W (permanently) and experiment with this mod.
The problem is I can’t seem to find/successfully make a usb connector that will fit under the dust bin.

I’ve spotted a couple of non-raspi mods that utilize the serial solder tabs on the main board as in the image link below. However, I’m too much of a n00b to figure out if it would work if I soldered the leads of a cut Micro-USB otg cable directly on there, and too scared I might fry the board if it doesn’t.

Does anybody know of a solution to this?

![](https://github.com/HawtDogFlvrWtr/botvac-wifi/blob/master/img/botvac-pins.jpg)

**Comment by jeroenterheerdt** [comment]
Not sure, does your BotVac 85 have a USB port on the outside? That's what you will need to use to get a serial connection going.

**Comment by JekleFPV** [comment]
Unfortunately not. On the Botvac the USB port is under the dustbin and the space is pretty cramped.
I’ve tried soldering my own cable together for it using a micro connector without the backshell, but it seems I’m frying the connector a bit too much in the process to get it working.

**Comment by jeroenterheerdt** [comment]
sorry, then I cannot help.

**Comment by JekleFPV** [comment]
Ok, here’s my the plan to work around this issue: 
Connect my pi zero to a [MAX3232 transceiver](https://www.antratek.nl/transceiver-breakout-max3232?___SID=U) to convert the signal, then connect that to the RS232 edge connector I mentioned earlier (the ‘solder tabs’).

I’ll give an update after I’ve got it hooked up and working!

**Comment by JekleFPV** [comment]
No need for the transceiver. Connect ground, GPIO 14 and GPIO 15 to the rx and tx as per the image below, with a 1K resistor on both the GPIOs.
![botvac-pins](https://user-images.githubusercontent.com/52248367/61065081-3efaed00-a403-11e9-8400-f31089157a15.jpg)
In raspi-config, interfacing, set the login shell to 'no', serial hardware to 'yes'.
Then use /dev/ttyS0 instead of /dev/ACM0, then it should work.
Unfortunately at least for now, I won't be able to test it.

**Comment by jeroenterheerdt** [comment]
awesome, thanks for sharing!
