### ISSUE TITLE
Legacy or State config with Home Assistant?

### ISSUE THREAD

**Issue by ericpoynter** [jeroenterheerdt/neato-serial#4]
I have this somewhat working with in Home Assistant. I am using mqtt and I can see it running on the Pi 3 and I can see the charge status and dock status in HA however, it does not respond to any commands I give it thru HA.  Should I be using the legacy or state vacuum mqtt config in HA? Neither seem to work.  I can't get the mqtt service to run on the Pi either but that is a separate issue.

**Comment by jeroenterheerdt** [comment]
have you tried running `neatoserialbasic.py` or `neatoserial.py` on the Pi attached to Neato?

**Comment by ericpoynter** [comment]
Yes, neatoserialbasic.py and neatoserial.py receives and  executes commands.  I can see in terminal that neatoserialmqtt.py  receives commands but does not execute them such as clean, return_to_base, locate.

**Comment by ericpoynter** [comment]
Ok, what's happening is that the vacuum is not responding to "wake-up". If I manually wake-up the vacuum and issue turn_on, it receives it but the LCD screen on the vacuum says that I need to "unplug the USB cable when I want to clean". If I unplug it, it starts cleaning.

**Comment by jeroenterheerdt** [comment]
that's why I included the option to use a relay or a direct connection - that should work to let Neato think the USB cable is disconnected so its starts cleaning.

**Comment by ericpoynter** [comment]
I have it all working with relay but it just will not wake-up in the interactive mode nor the mqtt mode. If I manual wake up the neato both methods work but that pretty much defeats the whole purpose of this. Perhaps I have a different software version. I am on 3.4.24079
